from django.db import models

class Data(models.Model):
    end_year = models.IntegerField(null=True)
    intensity = models.IntegerField(null=True)
    sector = models.CharField(max_length=30, null=True)
    topic = models.CharField(max_length=30)
    insight = models.CharField(max_length=300, null=True)
    url = models.CharField(max_length=255, null=True)
    region = models.CharField(max_length=30, null=True)
    start_year = models.IntegerField(null=True)
    impact = models.IntegerField(null=True)
    added = models.DateTimeField()
    published = models.DateTimeField(null=True)
    country = models.CharField(max_length=30)
    relevance = models.IntegerField(null=True)
    pestle = models.CharField(max_length=20, null=True)
    source = models.CharField(max_length=50, null=True)
    title = models.CharField(max_length=255)
    likelihood = models.IntegerField(null=True)