# Generated by Django 4.2.1 on 2023-05-20 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0002_alter_data_end_year_alter_data_impact_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='url',
        ),
    ]
