# Generated by Django 4.2.1 on 2023-05-20 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0003_remove_data_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='url',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
