# Generated by Django 4.2.1 on 2023-05-20 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0004_data_url'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Data',
        ),
    ]
